Fixing #58 and #59
pie-dao/pie-smart-pools pull request #60
Opened 2020-09-05 16:45 UTC by Evert0x

##### Description
Fix two issues with extras, including potential bug.

##### Refers/Fixes
Fixing #58 in the first 2 commits

Fixing #59 in the last 3 commits
`9fc36f40` is making sure `pokeWeights` can not be called after the weight adjustment has finished. 
`8f8009e` is making sure current weight adjustments are canceled after deleting a token 
`316708` is making sure current weight adjustments are canceled after adding a token

2020-09-06 17:29 UTC, Alexintosh approved these changes

2020-09-06 17:30 UTC, Alexintosh commented
Great PR, looking good to me. Adding @MickdeGraaf for review as well.

2020-09-07 08:55 UTC, MickdeGraaf requested changes
Can we also set startBlock to 0 on `bind`, `unbind`, `rebind` and all other functionality which touches the weights?

2020-09-07 19:47 UTC, Evert0x commented
Good feedback Mick. I've updated my pull request.

2020-09-08 10:56 UTC, MickdeGraaf approved these changes

2020-09-08 11:01 UTC, MickdeGraaf commented
Looks good. I'm merging and tagging a release.

2020-09-08 11:01 UTC, merged